### ISSUE TITLE
Опечатка на главной странице личного кабинета ученика

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#129]
**Описание**

Опечатка на кнопке Отправить комментарий на главной странице личного кабинета ученика

**Критичность** 

Тривиальная

**Локация дефекта**

https://github.com/Neto-Solutions/CrystalPuzzles/blob/3cb436a7a0505b0d47d3f12432597d111fd2a133/frontend/src/features/feedback/ui/student/Feedback.jsx#L12

**Шаги воспроизведения**

1. Клонировать на локальный репозиторий проект 
2. Перейти в ветку test 
3. В командной строке запустить контейнеры docker-compose up -d
4. Открыть http://localhost:8080/
5. Зайти под учеником 
"email": "student@crystal.com"
"password": "studentpass"

**Ожидаемый результат:**  на кнопке текст "Отправить комментарий"

**Фактический результат:** на кнопке текст "Отправить комментрарий"

**Скриншот**

![image](https://github.com/Neto-Solutions/CrystalPuzzles/assets/103563116/c85e420b-2947-4043-8265-6ed598b00e83)

**Окружение**
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 125.0.6422.142 (Официальная сборка), (64 бит)
ПО: IntelliJ IDEA 2022.3.2 (Community Edition)
	Docker Desktop version 4.21.1 (114176)

**Comment by saetovdinar** [comment]
Исправил

**Comment by 8highflyer8** [comment]
Закрыл
