### ISSUE TITLE
При входе с неверным паролем появлятся небезопасное сообщение об ошибке

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#161]
При входе с неверным паролем на странице авторизации появлятся небезопасное сообщение об ошибке "Неверный пароль", а должно быть "Неверное сочетание логина и пароля"

**Критичность** 

Значительная

**Локация дефекта**

<div class="LogReg_error__-4pb0">Неверный пароль</div>

**Шаги воспроизведения**

1. Открыть страницу авторизации http://203.31.40.34/
2. Зайти под тренером, ввести верный логин и неверный пароль
"email": "trainer@crystal.com"
"password": "trainerpass1"

**Ожидаемый результат:**  появилось сообщение "Неверное сочетание логина и пароля"

**Фактический результат:** появилось сообщение "Неверный пароль"

**Скриншот**

![image](https://github.com/user-attachments/assets/1921d186-07ca-4c2d-bb43-4f4e2514d138)

**Окружение**
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 126.0.6478.182 (Официальная сборка), (64 бит)

**Comment by einsy-dev** [comment]
Исправленно

**Comment by 8highflyer8** [comment]
Закрыл
