### ISSUE TITLE
Создание предварительных макетов

### ISSUE THREAD

**Issue by Annazvereva94** [Neto-Solutions/CrystalPuzzles#2]
Создание предварительных макетов, для согласования с заказчиком для приложения размер экрана для компьютера: 1920 px, и нужна еще мобильная версия 360 px.

-Регистрация, вход, выход, смена пароля, восстановление пароля

- 3 личных кабинета: методист, преподаватель, родители. 

- бумажные чек листы: https://drive.google.com/drive/folders/1o7lnvbxYip1KgjXo0wAYgFg6Hif7PSYF которые надо цифровизовать для отслеживания прогресса ребенка 
-
@Annazvereva94

**Comment by homutovan** [comment]
Макеты созданы, направлены на согласование заказчику 19.01.2024
