### ISSUE TITLE
Нет крестика для закрытия popup Мои награды

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#212]
**Описание**

На главной странице ученика при нажатии на блок Мои наград нет крестика для закрытия окна

**Критичность** 

Значительная

**Локация дефекта**

[frontend/src/pages/student/Main/Reward](https://github.com/Neto-Solutions/CrystalPuzzles/blob/test/frontend/src/pages/student/Main/Reward/Reward.jsx#L4)

**Шаги воспроизведения**

1. Клонировать на локальный репозиторий проект 
2. Перейти в ветку test 
3. В командной строке запустить контейнеры docker-compose up -d
4. Открыть http://localhost:8080/
5. Зайти под учеником 
"email": "student@crystal.com"
"password": "studentpass"
6. Нажать на блок Мои награды
7. Закрыть появившийся popup

**Ожидаемый результат:** Крестик есть, при нажатии popup закрывается

**Фактический результат:** Нет крестика для закрытия окна, popup закрывается только при нажитии за его границами

**Скриншот**
![image](https://github.com/user-attachments/assets/8411fddd-1431-40ce-ad96-335d5355fef1)

**Окружение**
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 127.0.6533.122 (Официальная сборка), (64 бит)
ПО: IntelliJ IDEA 2022.3.2 (Community Edition)
	Docker Desktop version 4.21.1 (114176)

**Comment by OlgaIts** [comment]
Не актуально. "Мои награды" - это теперь страница, а не модальное окно.

**Comment by 8highflyer8** [comment]
ок

**Comment by 8highflyer8** [comment]
ок
