### ISSUE TITLE
API group

### ISSUE THREAD

**Issue by homutovan** [Neto-Solutions/CrystalPuzzles#22]
Требуется разработать API для сущности group, предусматривающую следующие возможности:
1. Создание группы;
2. Изменение группы по id;
3. Удаление группы по id;
4. Вывод всех групп
5. Добавление участника в группу;
6. Удаление участника из группы; 
7. Получение группы по id.

**Comment by batMaxCom** [comment]
- Добавлены endpoints:
		- POST /api/v1/group/
		- GET /api/v1/group/{group_id}
- Создан ModelManager для управления моделями БД без прямого обращения к SQLAlchemy в роутерах,
- Создана функция ограничения доступа по ролям.

**Comment by batMaxCom** [comment]
- Добавлены endpoints:
		- GET /api/v1/group/ - Получение всех групп
		- PUT /api/v1/group/{group_id}
		- DELETE /api/v1/group/{group_id}
- Создан AsyncModelManager для управления моделями БД асинхронно

**Comment by batMaxCom** [comment]
- Добавлены endpoints:
		- Profile:
				- GET [/api/v1/profile/] - профиль пользователя
				- POST[/api/v1/profile/change-password/] - изменение пароля
				- GET[/api/v1/profile/edit/]- данные для редактирования на фронте
				- PUT[/api/v1/profile/edit/] - редактирование данных
				- PUT[/api/v1/profile/remove/] - удаление пользователя (is_active=false)
				- PUT[/api/v1/profile/set-photo/] - добавить пользователю фото(храниться в БД в байтовом формате)
				- PUT[/api/v1/profileremove-photo/] - удалить фото пользователя
				- GET[/api/v1/profile/get-photo/] - показать фото пользователя (в байтовом формате)
- Обновлено поле `photo` таблицы Users:
		- **str**->**bytes**
