### ISSUE TITLE
При входе под админом сайт блокируется

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#231]
**Описание**

При входе под админом сайт виснет, мигает и нет возможности выйти

**Критичность** 

Блокирующий

**Локация дефекта**

/static/js/widgets/sidebar/navMenu/NavMenu.tsx
/static/node_modules/react-dom/cjs/react-dom.production.min.js

**Шаги воспроизведения**

1. Клонировать на локальный репозиторий проект 
2. Перейти в ветку test 
3. В командной строке запустить контейнеры docker-compose up -d
4. Открыть http://localhost:8080/
5. Зайти под админом 
"email": "admin@crystal.com"
"password": "adminpass"

**Ожидаемый результат:** Открылась главная страница админа

**Фактический результат:** Сайт виснет, мигает и нет возможности выйти

**Скриншот**

![image](https://github.com/user-attachments/assets/96c9b8aa-ac67-4465-94bd-538a263a1704)
![image](https://github.com/user-attachments/assets/e46e96dc-ecf5-4787-9844-a4650a30357b)

**Скринкаст**

https://github.com/user-attachments/assets/f09c58fb-239b-427f-841d-a37f0da8669d

**Окружение**

Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 127.0.6533.122 (Официальная сборка), (64 бит)
ПО: IntelliJ IDEA 2022.3.2 (Community Edition)
	Docker Desktop version 4.21.1 (114176)

**Comment by einsy-dev** [comment]
Убрана возможно войти под админом
