### ISSUE TITLE
При смене аватара граница блока перекрывает сообщение об ошибке

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#252]
**Описание**

При смене аватара учеником граница блока перекрывает сообщение об ошибке

**Критичность** 

Значительная

**Локация дефекта**
https://github.com/Neto-Solutions/CrystalPuzzles/blob/c03ab39285edacc5c36062a7dc0b0104376f904e/frontend/src/pages/shared/Avatar/Avatar.module.scss#L51

**Шаги воспроизведения**

1. Клонировать на локальный репозиторий проект 
2. Перейти в ветку test 
3. В командной строке запустить контейнеры docker-compose up -d
4. Открыть http://localhost:8080/
5. Зайти под учеником 
"email": "student@crystal.com"
"password": "studentpass"
6. В сайдбаре нажать на "Изменить аватарку"
7. Нажать кнопку "Загрузить"
8. Загрузить фото в формате .jpg 19 МБ
https://drive.google.com/file/d/1GyZZ95YgS7T4IxBdzRBjIh2Kfq3brnju/view?usp=sharing
9. Нажать кнопку "Сохранить"

**Ожидаемый результат:**  Сообщение внутри блока

**Фактический результат:** Граница блока перекрывает сообщение об ошибке

**Скриншот**
![image](https://github.com/user-attachments/assets/32daed47-3010-4de2-bc8b-0eac6d359845)

**Окружение**
Lenovo B51-80
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 129.0.6668.71 (Официальная сборка), (64 бит)

**Comment by OlgaIts** [comment]
Не актуально. Такой страницы больше нет. 
Теперь так:

![Screenshot_1](https://github.com/user-attachments/assets/3ec10fff-c1c7-4eb5-b0ea-90247311b4c1)

**Comment by 8highflyer8** [comment]
Закрываю
