### ISSUE TITLE
Не отображается фото ученика на аватаре

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#259]
На главной странице ученика на аватаре не отображется фото ученика

**Критичность** 

Значительная

**Локация дефекта**
img src="http://203.31.40.34/pages/photo/3/24-10-03T06-37-14.jpeg" class="Account_avatar__4VqsI" alt=""

**Шаги воспроизведения**

1. Открыть http://203.31.40.34/
2. Зайти под учеником
"email": "student@crystal.com"
"password": "studentpass"

**Ожидаемый результат:** Отображается фото

**Фактический результат:** Фото не отображается

**Скриншот**

![image](https://github.com/user-attachments/assets/d73c4364-fe27-4b5e-8ba5-dc7ad165d4ec)

**Окружение**
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 129.0.6668.89 (Официальная сборка), (64 бит)

**Comment by einsy-dev** [comment]
Исправленно
