### ISSUE TITLE
В разделе Мои личные данные не отображется фото ученика

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#260]
**Описание**

В разделе Мои личные данные не отображется фото ученика

**Критичность**

Значительная

**Локация дефекта**

img class="Profile_avatar__EyaF+" src="http://203.31.40.34/pages/photo/3/24-10-03T06-37-14.jpeg"

**Шаги воспроизведения**

1. Открыть http://203.31.40.34/
2. Зайти под учеником
"email": "[student@crystal.com](mailto:student@crystal.com)"
"password": "studentpass"
3. Нажать на аватар слева вверху

**Ожидаемый результат:** Отображается фото

**Фактический результат:** Фото не отображается

**Скриншот**
![image](https://github.com/user-attachments/assets/b529c6c1-3a7e-47b6-b871-07b41ad34a81)

**Окружение**
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 129.0.6668.89 (Официальная сборка), (64 бит)

**Comment by einsy-dev** [comment]
Исправленно

**Comment by 8highflyer8** [comment]
Закрыл
