### ISSUE TITLE
Разные персонажи в мобильной и десктоп версии на странице ученика

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#262]
**Описание**

На главной странице ученика в блоке Мои награды при ширине экрана 840 px и менее лисенок,  больше 840 px - единорог

**Критичность**

Незначительная

**Локация дефекта**

a class="Card_link_card__bWeMf Main_reward_card__SUjvD" href="/reward"> </a

**Шаги воспроизведения**

1. Открыть http://203.31.40.34/
2. Зайти под учеником
"email": "[student@crystal.com](mailto:student@crystal.com)"
"password": "studentpass"
3. Сделать ширину экрана в Devtools 840 px
4. Сделать ширину экрана в Devtools 841 px

**Ожидаемый результат:**  В блоке Мои награды лисенок и при измеение размера экрана персонаж не меняется.

**Фактический результат:** Лисенок меняется на единорога при увеличении экрана более 840 px

**Скриншот**
![image](https://github.com/user-attachments/assets/8fd05f98-3907-4785-be0e-ad666bf2e9b0)
![image](https://github.com/user-attachments/assets/4ebdb4d2-1dfe-49c6-90d1-1b324b621a7e)

**Окружение**
Операционная система: Windows 10 Pro 22H2 сборка 19045.2130
Браузер: Chrome Версия 129.0.6668.89 (Официальная сборка), (64 бит)

**Comment by OlgaIts** [comment]
Исправлено

**Comment by 8highflyer8** [comment]
Спс. Закрыл

**Comment by 8highflyer8** [comment]
Спс. Закрыл
