### ISSUE TITLE
В мобильной версии у методиста нет отступа между версией продукта и Оценочной таблицы эффективности

### ISSUE THREAD

**Issue by 8highflyer8** [Neto-Solutions/CrystalPuzzles#272]
**Описание**

В мобильной версии у методиста нет отступа между версией продукта и заголовком Оценочная таблица эффективности

**Критичность** 

Незначительная

**Локация дефекта**

http://203.31.40.34/evaluation

**Шаги воспроизведения**

1. Открыть http://203.31.40.34/
2. Зайти под методистом
   email: supervisor@crystal.com
   password: supervisorpass
3. На главной странице тапнуть на Таблицу в сайдбаре

**Ожидаемый результат:**  Отступ есть, есть выравнивание по центру по горизонтали

**Фактический результат:** Отступа нет, нет выравнивание по центру по горизонтали

**Скриншот**

![image](https://github.com/user-attachments/assets/3de201e9-ff2c-4ecf-bd4c-86be6e1b0374)

**Окружение**
Galaxy A52
Операционная система: Android 14
Браузер: Chrome Версия 129.0.6668.100

**Comment by einsy-dev** [comment]
исправлено, версия перенесена вниз страницы

**Comment by 8highflyer8** [comment]
Закрыл
